name: Hello world
on:
  push:
    branches: 
      - main
      - develop
      
#on pushing to any main branch trigger will run #workflow_dispatch --> This is the manual trigger
 #this is the manual trigger kind of it's event trigger
jobs:
  hello: #this is the job name 
    runs-on: ubuntu-latest #we are specifying where to run runner
    steps:
      - name: Hello
        run: | # this one line command -->echo "Welcome to Hello world work flow" 
          echo "This is first command"
          echo "this is second command" # | --> Using this symbol we can write multiple command
    #Git hub actions by default run the workdflow in parallell
    # to need to run serial we need to add the needs command
  build:
    runs-on: ubuntu-latest
    needs: hello
    steps:
      - name: Building the code
        run: echo "This is the code block of buldings"
        
     
    
