name: Hello world
on: workflow_dispatch #this is the manual trigger kind of it's event trigger
jobs:
  hello: #this is the job name 
    runs-on: ubuntu-latest #we are specifying where to run runner
    steps:
      - name: Hello
        run: | # this one line command -->echo "Welcome to Hello world work flow" 
          echo "This is first command"
          echo "this is second command" # | --> Using this symbol we can write multiple command
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Building the code
        run: echo "This is the code block of buldings"
        
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Test Build
        run:  echo "This is the test code."
  
     
    
